# Generated by Django 4.2.1 on 2023-08-25 20:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_name", models.CharField(max_length=100)),
                ("asset_manufacturer", models.CharField(max_length=100)),
                (
                    "asset_purchased_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("asset_condition", models.TextField()),
                ("asset_issued", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["asset_purchased_date"],
            },
        ),
        migrations.CreateModel(
            name="CompanyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=100)),
                ("employee_department", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to="assets.companymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_date", models.DateTimeField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("checkout_condition", models.TextField()),
                ("return_condition", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assetlog",
                        to="assets.assetsmodel",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employeelog",
                        to="assets.employeemodel",
                    ),
                ),
            ],
        ),
    ]
