# Generated by Django 4.2.1 on 2023-08-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetslog",
            name="checkout_condition",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetslog",
            name="checkout_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetsmodel",
            name="asset_condition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
