# Generated by Django 4.2.1 on 2023-08-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_alter_assetslog_checkout_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetslog",
            name="checkout_condition",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="assetslog",
            name="checkout_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="assetsmodel",
            name="asset_condition",
            field=models.TextField(),
        ),
    ]
