# Generated by Django 4.2.1 on 2023-08-25 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_assetslog_checkout_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetslog",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assetlog",
                to="assets.assetsmodel",
            ),
        ),
    ]
