# Generated by Django 4.2.1 on 2023-08-25 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0005_alter_assetslog_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetslog",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset",
                to="assets.assetsmodel",
            ),
        ),
        migrations.AlterField(
            model_name="assetslog",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="assets.employeemodel",
            ),
        ),
    ]
